import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
//import { Geist, Geist_Mono , Poppins , Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "COE Access",
  description: "Generated by create next app",
};

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "700"] }
);


// const roboto = Roboto({ 
//   subsets: ["latin"], 
//   weight: ["500", "700"] }
// );

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

interface RootLayoutProps {
  children: ReactNode;
}



export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}