# Database 
version: "3.8"
name: COE_Room_AcessControl
services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  authen_backend:
    build:
      context: ./Backend    # โฟลเดอร์ที่มี Dockerfile สำหรับ Flask
      dockerfile: authen/dockerfile.authen
    container_name: authen_backend
    ports:
      - "5000:5000"           # map port 5000 ของ container กับเครื่อง host
    volumes:
      - ./certificates:/app/authen/certificates 
    environment:
      - FLASK_ENV=development  # ตั้งค่า environment สำหรับ Flask (เปลี่ยนเป็น production เมื่อต้องการ)
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/mydb
      - GOOGLE_CLIENT_ID=1033311153846-985omsfscb3beu6u42c0qpo6k6m5vheg.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      - db                    # รอให้บริการฐานข้อมูลพร้อมก่อน backend เริ่มทำงาน
  room_manage_backend:
    build:
      context: ./Backend
      dockerfile: room_manage/dockerfile.room
    container_name: room_manage_backend
    ports:
      - "5001:5001"
    volumes:
      - ./certificates:/app/room_manage/certificates 
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/mydb
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend      # ชี้ไปที่โฟลเดอร์ frontend ที่มี Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules        # mount โค้ดจากเครื่อง host ไปที่ /app ใน container
      - frontend_next:/app/.next       # ใช้ anonymous volume สำหรับ node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_AUTH_URL=https://localhost:5000  # สำหรับ Authentication
      - NEXT_PUBLIC_API_ROOM_URL=https://localhost:5001  # สำหรับ Room Management
    command: npm run dev
    depends_on:
      - authen_backend
      - room_manage_backend

volumes:
  db_data:
  frontend_node_modules:  # เพิ่ม Named Volume สำหรับ node_modules
  frontend_next:  # เพิ่ม Named Volume สำหรับ .next