# Database 
version: "3.8"
name: coe_room_acesscontrol
services:
  auth_db:
    image: postgres:13
    container_name: my_auth_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  room_req_db:
    image: postgres:13
    container_name: my_room_req_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: room_req_db
    ports:
      - "5433:5433"
    volumes:
      - room_req_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U myuser -d room_req_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  room_mgmt_db:
    image: postgres:13
    container_name: my_room_mgmt_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: room_mgmt_db
    ports:
      - "5434:5432"
    volumes:
      - room_mgmt_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d room_mgmt_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  authen_backend:
    build:
      context: ./Backend   
      dockerfile: authen/dockerfile.authen
    container_name: authen_backend
    ports:
      - "5000:5000"           
    #volumes:
    #  - ./certificates:/app/authen/certificates 
    environment:
      - FLASK_ENV=development  
      - DATABASE_URL=postgresql://myuser:mypass@auth_db:5432/auth_db
      - SECRET_KEY=60aed22ea8229e5b975d51423e6e4926e198b3afb14aec9e09e1ee5340cb976a
      - GOOGLE_CLIENT_ID=1033311153846-985omsfscb3beu6u42c0qpo6k6m5vheg.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
        auth_db:
          condition: service_healthy                  
    networks:
      - app-network

  room_req_backend:
    build:
      context: ./Backend
      dockerfile: room_request/dockerfile.req
    container_name: room_req_backend
    restart: always
    ports:
      - "5001:5001"
    #volumes:
    #  - ./certificates:/app/room_request/certificates 
    environment:
      - FLASK_ENV=development
      - DATABASE_ROOM_URL=postgresql://myuser:mypass@room_req_db:5432/room_req_db
      - SECRET_KEY=60aed22ea8229e5b975d51423e6e4926e198b3afb14aec9e09e1ee5340cb976a
    depends_on:
      room_req_db:
        condition: service_healthy
      authen_backend:
        condition: service_started
    networks:
      - app-network

  room_mgmt_backend:
    build:
      context: ./Backend
      dockerfile: room_mgmt/dockerfile.mgmt
    container_name: room_mgmt_backend
    restart: always
    ports:
      - "5002:5002"
    #volumes:
    #  - ./certificates:/app/room_request/certificates 
    environment:
      - FLASK_ENV=development
      - DATABASE_ROOM_URL=postgresql://myuser:mypass@room_mgmt_db:5432/room_mgmt_db
      - SECRET_KEY=60aed22ea8229e5b975d51423e6e4926e198b3afb14aec9e09e1ee5340cb976a
    depends_on:
      room_mgmt_db: 
        condition: service_healthy
      authen_backend:
        condition: service_started
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend      
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Sync โค้ดแบบ Realtime
      - frontend_node_modules:/app/node_modules  
      - frontend_next:/app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - NEXT_PUBLIC_API_AUTH_URL=http://localhost:5000  # สำหรับ Authentication
      - NEXT_PUBLIC_API_REQ_URL=http://localhost:5001  # สำหรับ Request Service
      - NEXT_PUBLIC_API_ROOM_URL=http://localhost:5002 # สำหรับ Room Mgmt
      - NEXT_PUBLIC_API_KEY_IMAGE=1852c3fd33edbe8c95231e5a74106018dcec3a448eacb0d9270f28821033ea4a # สำหรับดึงรูปจากกลุ่ม 1
    command: npm run dev
    depends_on:
      - authen_backend
      - room_req_backend
    networks:
      - app-network
    stdin_open: true  # ป้องกันปัญหากับ npm run dev
    tty: true         # ให้ container รันแบบ interactive

volumes:
  auth_db_data:
  room_req_db_data:
  room_mgmt_db_data:
  frontend_node_modules:  
  frontend_next:  

networks:
  app-network:
    driver: bridge