FROM python:3.9-slim

WORKDIR /app/room_request

COPY room_request/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY room_request/ .

EXPOSE 5001

CMD ["python", "room_request.py"]