FROM python:3.9-slim

WORKDIR /app/room_manage

COPY room_manage/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY room_manage/ .

EXPOSE 5001

CMD ["python", "room_manage.py"]